apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloendoworld
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: helloendoworld
          image: sanmiguelsan/helloendoworld:withshutdown
          ports:
            - containerPort: 8080
              protocol: TCP
