apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloendoworld-deployment
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: helloendoworld
          image: docker.io/sanmiguelsan/helloendoworld:V8Shut30
          ports:
            - containerPort: 8080
              protocol: TCP
      #terminationGracePeriodSeconds: 30
      #restartPolicy: Never
      #INVESTIGATE on RESTART POLICY!! or backoffLimit
          #lifecycle:
          #    preStop:
          #      exec:
          #        command: ["curl localhost:8080/shutdown/"]
