apiVersion: batch/v1
kind: Job
metadata:
  name: helloendoworld-job
spec:
  #selector:
    #matchLabels:
      #run: helloendoworld-batch
  backoffLimit: 5
  activeDeadlineSeconds: 30
  #replicas: 2
  template:
    spec:
      containers:
      - name: helloendoworld
        image: docker.io/sanmiguelsan/helloendoworld:V8Shut30
        ports:
          - containerPort: 8080
            protocol: TCP
      restartPolicy: Never
